### ISSUE TITLE
Dominus troops cause 0loss battles when on the same hex

### ISSUE THREAD

**Issue by lvpcguru** [dan335/dominus#16]
![noerror](https://user-images.githubusercontent.com/4685333/55633091-94cb5380-5789-11e9-8712-57f3717ff944.png)

![error_attackAlerts](https://user-images.githubusercontent.com/4685333/55633004-7e24fc80-5789-11e9-9e69-0bb23bd16ecb.png)

Attack alerts are generated any time the Dominus troops are in the same hex. This also adds a bunch of 0 loss battles to go with it.

an example:
https://dominusgame.net/game/GXz5pcQSvkpcR4Qu2/battle/XK4cBamorjW2PXrmA

**Comment by lvpcguru** [comment]
Could this be related to at least the create new army in the same hex that already has one cause for this issue? 
https://github.com/dan335/dominus/blob/2a112cd5dec8901c1ef96c0dd7130bc767dc2d18/packages/dominus-armies/server/armyServerFunctions.js#L281

maybe add the armys player ID to the check here? like the army.isEnemy(otherArmy) checks in the battle jobs

if ((otherArmy._id != army._id) && (this.playerId == otherArmy.playerId)) {

**Comment by dan335** [comment]
Thanks for figuring that out!  Closing this.
