### ISSUE TITLE
Password recovery email title has "undefined"

### ISSUE THREAD

**Issue by serv** [dan335/dominus#169]
![screen shot 2015-02-23 at 11 06 41 am](https://cloud.githubusercontent.com/assets/103456/6334899/7870be9c-bb4c-11e4-9ea6-432fe3b1cb77.png)

Notice the password reads: How to reset your password on undefined.

I am not sure what the value for undefined should be , but definitely a bug

**Comment by dan335** [comment]
Fixed it, thanks Jason.
