### ISSUE TITLE
Text underline artefacts on landing page footers

### ISSUE THREAD

**Issue by ollyfg** [dan335/dominus#214]
The social buttons have funny underlines (look like dashes) next to them either normally or when you hover over them, depending on what page you're on. 
The join game page can be fixed by a 1 liner of css, I would submit a PR but I couldn't any css (or .less) files that looked like they should be edited (the ones I found said not to edit them).

Just add `#landingFooter .landingPad a:hover{text-decoration:none;}`

Here is the page as it is: (mouse drawn on as it disappears during screenshots)
![broken_page](https://cloud.githubusercontent.com/assets/8495389/9217654/6debf326-411e-11e5-8848-bd0bf3b2f5b1.png)

And here is the fixed one:
![fixed_page](https://cloud.githubusercontent.com/assets/8495389/9217664/8809bb8a-411e-11e5-8249-b24388db4f4a.png)

**Comment by dan335** [comment]
I've been wondering what those were from.  Thanks!  Haven't had a chance to look into it.  I'll get the fix in soon.

**Comment by dan335** [comment]
Will be fixed next time I update, thanks.
