### ISSUE TITLE
Army overview in summary, shield/no shield bug

### ISSUE THREAD

**Issue by Zacky1** [dan335/dominus#216]
In the "Armies" overview in the summary tab, it seems like some armies get a shield icon while others don't, although they have the same properties: on vassal castle hexes, same soldier count.

![untitled](https://cloud.githubusercontent.com/assets/1578397/10414609/3a66f954-6fab-11e5-8abd-919c49c77280.jpg)

As you can see from the picture, army "Protectorate B" is on one of my vassals, yet in the armies overview the shield isn't present. 

Whereas Protectorate C (the army on the castle on the upper part of the picture) has the shield icon.

**Comment by Zacky1** [comment]
P.s. I made the same forum post, but I wasn't sure if you looked at those at all, and I was thinking a picture would help.

**Comment by dan335** [comment]
Pretty sure this is fixed.
